# Generated by Django 5.0.6 on 2024-05-29 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HockeyTeams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50, null=True)),
                ('year', models.SmallIntegerField(null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('losses', models.SmallIntegerField(blank=True, null=True)),
                ('ot_losses', models.CharField(blank=True, max_length=50, null=True)),
                ('win_percent', models.FloatField(blank=True, null=True)),
                ('goals_for', models.IntegerField(blank=True, null=True)),
                ('goals_against', models.IntegerField(blank=True, null=True)),
                ('plus_minus', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OscarFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('nominations', models.IntegerField(blank=True, null=True)),
                ('awards', models.IntegerField(blank=True, null=True)),
                ('best_picture', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
