# Generated by Django 5.0.6 on 2024-05-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraperscript', '0002_oscarfilms_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSpoofResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True)),
                ('response', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
